# name: Reviewer Approval Check

# on:
#   pull_request:
#     branches:
#       - '**'  # Trigger on all PRs targeting any branch
#   pull_request_review:
#     types: [submitted]

# jobs:
#   approval:
#     name: Reviewer
#     runs-on: ubuntu-latest

#     steps:
#       - name: Debug Message
#         run: echo "✅ This workflow is triggered correctly"

#       - name: Check if PR is approved by TL or Sr Developer
#         env:
#           REVIEWER_NAME: ${{ secrets.REVIEWER_NAME }}  # e.g., RajCamrix,TrushangKCMX
#         uses: actions/github-script@v6
#         with:
#           github-token: ${{ secrets.GITHUB_TOKEN }}
#           script: |
#             const requiredUsers = process.env.REVIEWER_NAME.split(',').map(s => s.trim());
#             const { data: reviews } = await github.rest.pulls.listReviews({
#               owner: context.repo.owner,
#               repo: context.repo.repo,
#               pull_number: context.payload.pull_request.number,
#             });

#             const approvedBy = reviews
#               .filter(r => r.state === 'APPROVED')
#               .map(r => r.user.login);

#             const isApproved = requiredUsers.some(user => approvedBy.includes(user));

#             if (!isApproved) {
#               core.setFailed(`❌ PR must be approved by one of: ${requiredUsers.join(', ')}. Approved by: ${approvedBy.join(', ') || 'no one'}`);
#             } else {
#               console.log(`✅ Approved by at least one required user.`);
#             }
        


name: Reviewer Approval Check

on:
  workflow_run:
    workflows: ["SonarQube Report"]
    types:
      - completed
  pull_request:
    branches:
      - '**'
  pull_request_review:
    types: [submitted]

jobs:
  approval:
    name: Reviewer
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'pull_request' || github.event_name == 'pull_request_review' }}
    runs-on: ubuntu-latest

    steps:
      - name: Debug: List all check runs
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const prNumber = context.payload.pull_request ? context.payload.pull_request.number : null;

            if (!prNumber) {
              console.log("🔍 No PR number found, possibly not a PR event.");
              return;
            }

            const { data: pr } = await github.rest.pulls.get({
              owner,
              repo,
              pull_number: prNumber
            });

            const headSha = pr.head.sha;

            const { data: checks } = await github.rest.checks.listForRef({
              owner,
              repo,
              ref: headSha
            });

            console.log("✅ Check runs for the latest commit:");
            for (const check of checks.check_runs) {
              console.log(`- ${check.name} | Status: ${check.status} | Conclusion: ${check.conclusion}`);
            }

      - name: Check SonarQube status
        id: sonar-status
        continue-on-error: true
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const prNumber = context.payload.pull_request ? context.payload.pull_request.number : null;

            if (!prNumber) {
              console.log("⚠️ Not a PR event. Skipping SonarQube check.");
              return;
            }

            const { data: pr } = await github.rest.pulls.get({
              owner,
              repo,
              pull_number: prNumber
            });

            const headSha = pr.head.sha;

            const { data: checks } = await github.rest.checks.listForRef({
              owner,
              repo,
              ref: headSha
            });

            const sonarCheck = checks.check_runs.find(c => c.name.includes("SonarQube Report"));

            if (!sonarCheck) {
              core.setFailed("❌ SonarQube check not found.");
              return;
            }

            if (sonarCheck.conclusion !== "success") {
              core.setFailed(`❌ SonarQube check failed or incomplete. Status: ${sonarCheck.conclusion}`);
              return;
            }

            console.log("✅ SonarQube passed. Proceeding with reviewer check.");

      - name: Check if PR is approved by TL or Sr Developer
        env:
          REVIEWER_NAME: ${{ secrets.REVIEWER_NAME }}  # Example: RajCamrix,TrushangKCMX
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const requiredUsers = process.env.REVIEWER_NAME.split(',').map(s => s.trim());
            const prNumber = context.payload.pull_request ? context.payload.pull_request.number : null;

            if (!prNumber) {
              console.log("⚠️ No PR context. Skipping approval check.");
              return;
            }

            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
            });

            const approvedBy = reviews
              .filter(r => r.state === 'APPROVED')
              .map(r => r.user.login);

            const isApproved = requiredUsers.some(user => approvedBy.includes(user));

            if (!isApproved) {
              core.setFailed(`❌ PR must be approved by one of: ${requiredUsers.join(', ')}. Approved by: ${approvedBy.join(', ') || 'no one'}`);
            } else {
              console.log(`✅ Approved by at least one required user.`);
            }