# name: Reviewer Approval Check

# on:
#   pull_request:
#     branches:
#       - '**'  # Trigger on all PRs targeting any branch
#   pull_request_review:
#     types: [submitted]

# jobs:
#   approval:
#     name: Reviewer
#     runs-on: ubuntu-latest

#     steps:
#       - name: Debug Message
#         run: echo "✅ This workflow is triggered correctly"

#       - name: Check if PR is approved by TL or Sr Developer
#         env:
#           REVIEWER_NAME: ${{ secrets.REVIEWER_NAME }}  # e.g., RajCamrix,TrushangKCMX
#         uses: actions/github-script@v6
#         with:
#           github-token: ${{ secrets.GITHUB_TOKEN }}
#           script: |
#             const requiredUsers = process.env.REVIEWER_NAME.split(',').map(s => s.trim());
#             const { data: reviews } = await github.rest.pulls.listReviews({
#               owner: context.repo.owner,
#               repo: context.repo.repo,
#               pull_number: context.payload.pull_request.number,
#             });

#             const approvedBy = reviews
#               .filter(r => r.state === 'APPROVED')
#               .map(r => r.user.login);

#             const isApproved = requiredUsers.some(user => approvedBy.includes(user));

#             if (!isApproved) {
#               core.setFailed(`❌ PR must be approved by one of: ${requiredUsers.join(', ')}. Approved by: ${approvedBy.join(', ') || 'no one'}`);
#             } else {
#               console.log(`✅ Approved by at least one required user.`);
#             }
        


name: Reviewer Approval Check

on:
  pull_request:
    branches:
      - '**'  # Trigger on all PRs targeting any branch
  pull_request_review:
    types: [submitted]

jobs:
  approval:
    name: Reviewer
    runs-on: ubuntu-latest

    steps:
      - name: Check SonarQube status
        id: sonar-status
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const prNumber = context.payload.pull_request.number;

            const { data: pr } = await github.rest.pulls.get({
              owner,
              repo,
              pull_number: prNumber
            });

            const headSha = pr.head.sha;

            const { data: checks } = await github.rest.checks.listForRef({
              owner,
              repo,
              ref: headSha
            });

            const sonarCheck = checks.check_runs.find(c => c.name.includes("SonarQube Report"));

            if (!sonarCheck) {
              core.setFailed("❌ SonarQube check not found.");
              return;
            }

            if (sonarCheck.conclusion !== "success") {
              core.setFailed(`❌ SonarQube check has not passed (status: ${sonarCheck.conclusion}). Skipping approval check.`);
              return;
            }

            console.log("✅ SonarQube passed. Proceeding with reviewer approval check.");

      - name: Debug Message
        run: echo "✅ This workflow is triggered correctly"

      - name: Check if PR is approved by TL or Sr Developer
        env:
          REVIEWER_NAME: ${{ secrets.REVIEWER_NAME }}  # e.g., RajCamrix,TrushangKCMX
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const requiredUsers = process.env.REVIEWER_NAME.split(',').map(s => s.trim());
            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });

            const approvedBy = reviews
              .filter(r => r.state === 'APPROVED')
              .map(r => r.user.login);

            const isApproved = requiredUsers.some(user => approvedBy.includes(user));

            if (!isApproved) {
              core.setFailed(`PR must be approved by one of: ${requiredUsers.join(', ')}. Approved by: ${approvedBy.join(', ') || 'no one'}`);
            } else {
              console.log(`Approved by at least one required user.`);
            }