# name: Reviewer Approval Check

# on:
#   pull_request:
#     branches:
#       - '**'  # Trigger on all PRs targeting any branch
#   pull_request_review:
#     types: [submitted]

# jobs:
#   approval:
#     name: Reviewer
#     runs-on: ubuntu-latest

#     steps:
#       - name: Debug Message
#         run: echo "✅ This workflow is triggered correctly"

#       - name: Check if PR is approved by TL or Sr Developer
#         env:
#           REVIEWER_NAME: ${{ secrets.REVIEWER_NAME }}  # e.g., RajCamrix,TrushangKCMX
#         uses: actions/github-script@v6
#         with:
#           github-token: ${{ secrets.GITHUB_TOKEN }}
#           script: |
#             const requiredUsers = process.env.REVIEWER_NAME.split(',').map(s => s.trim());
#             const { data: reviews } = await github.rest.pulls.listReviews({
#               owner: context.repo.owner,
#               repo: context.repo.repo,
#               pull_number: context.payload.pull_request.number,
#             });

#             const approvedBy = reviews
#               .filter(r => r.state === 'APPROVED')
#               .map(r => r.user.login);

#             const isApproved = requiredUsers.some(user => approvedBy.includes(user));

#             if (!isApproved) {
#               core.setFailed(`❌ PR must be approved by one of: ${requiredUsers.join(', ')}. Approved by: ${approvedBy.join(', ') || 'no one'}`);
#             } else {
#               console.log(`✅ Approved by at least one required user.`);
#             }
        
 
name: Reviewer

on:
  workflow_run:
    workflows: ["SonarQube Report"]
    types:
      - completed

jobs:
  reviewer-approval:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    name: Check PR Reviewer

    steps:
      - name: Get PR Info from Branch
        uses: actions/github-script@v6
        id: get-pr
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const run = await github.rest.actions.getWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.payload.workflow_run.id,
            });

            const branch = run.data.head_branch;
            const pulls = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              head: `${context.repo.owner}:${branch}`,
            });

            if (pulls.data.length === 0) {
              core.setFailed('No matching PR found for this branch');
              return;
            }

            const pr = pulls.data[0];
            core.setOutput('pr_number', pr.number);

      - name: Check Reviewer Approval
        uses: actions/github-script@v6
        env:
          REVIEWER_NAME: ${{ secrets.REVIEWER_NAME }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = core.getInput('pr_number');
            const reviewers = process.env.REVIEWER_NAME.split(',').map(r => r.trim());

            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
            });

            const approvedBy = reviews
              .filter(r => r.state === 'APPROVED')
              .map(r => r.user.login);

            const isApproved = reviewers.some(user => approvedBy.includes(user));

            if (!isApproved) {
              core.setFailed(`❌ PR must be approved by: ${reviewers.join(', ')}. Approved by: ${approvedBy.join(', ') || 'no one'}`);
            } else {
              console.log(`✅ Approved by: ${approvedBy.join(', ')}`);
            }

